core/urls.py
from django.urls import path, re_path
from .views import IndexView, AboutView, ContactView, ServiceDetailView, ServicesListView, ArticleListView, ArticleDetailView
app_name = 'core'

urlpatterns = [ 

    path('', IndexView.as_view(), name='index'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutView.as_view(), name='about'),
    path('articles/', ArticleListView.as_view(), name='articles'),
    path('article_detail/<slug:slug>/', ArticleDetailView.as_view(), name='article_detail'), 
    path('services/', ServicesListView.as_view(), name='services'),
    path('services/<slug:slug>/', ServiceDetailView.as_view(), name='service-detail'),
    # path('admin/core/invoice/<int:invoice_id>/', admin_order_detail, name='admin_order_detail'),
    # path('admin/core/invoice/<int:invoice_id>/pdf/', admin_order_pdf, name='admin_order_pdf'),
] 

core/models.py
from telnetlib import RCP
from django.db import models
# Create your models here.
from tinymce import models as tinymce_models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)

class Category(models.Model):
    name  = models.CharField(verbose_name=_('Nom du DAS'), max_length=100)
    title  = models.CharField(verbose_name=_('Petit text'), max_length=100, blank=True, null=True)
    description = models.TextField(verbose_name=_("Description"), blank=True, null=True)
    icon  = models.FileField(upload_to='images/categories', null=True, blank=True)
    
    class Meta:
        verbose_name ="Catégorie"
    
    def __str__(self):
        return self.name

class Solution(models.Model):
    name        = models.CharField(verbose_name=_('sous catégorie'), max_length=100)
    title       = models.TextField(verbose_name=_('Petit text'),blank=True, null=True)
    description = tinymce_models.HTMLField(verbose_name='Déscription du produit', blank=True, null=True)
    icon        = models.ImageField(upload_to='images/categories', null=True, blank=True)
    def __str__(self):
        return self.name

class Service(models.Model):
    name  = models.CharField(verbose_name=_('Nom du Service'), max_length=100)
    slug = models.SlugField()
    title  = models.CharField(verbose_name=_('Petit text'), max_length=300)
    photo  = models.ImageField(upload_to="images/services",verbose_name=_('img 2'),blank=True, null=True)
    image = models.FileField( upload_to="images/services/", blank=True, null=True)
    category = models.ForeignKey(Category, verbose_name=_("DAS categorie"), on_delete=models.CASCADE)
    description = tinymce_models.HTMLField(verbose_name='Déscription du produit', blank=True, null=True)
    icon  = models.CharField(verbose_name=_('nom de l icon du site https://fontawesome.com/icons'), max_length=100)
    priority  = models.IntegerField(verbose_name=_('ordre / priorité'))
    to_home_page = models.BooleanField(verbose_name="ajouter a la page d'accueil", default=False)
    to_footer = models.BooleanField(verbose_name="ajouter au footer", default=False)
    # actif  = models.BooleanField(default=True)
    # created      = models.DateTimeField(verbose_name='Date de Création',  auto_now_add=True)
    # updated      = models.DateTimeField(verbose_name='Date de dernière mise à jour',  auto_now=True)
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("core:service-detail", kwargs={"slug": self.slug})
    
# class Article(models.Model):
#     pass                    

class Contact(models.Model):
    name        = models.CharField(verbose_name=_('Nom complet'), max_length=100)
    phone       = models.CharField(verbose_name=_("Téléphone") , max_length=25)
    email       = models.EmailField(verbose_name=_("Email"), null=True, blank =True)
    subject     = models.CharField(verbose_name=_("Sujet"), max_length=50, blank=True,null=True)
    message     = models.TextField(verbose_name=_("Message"), blank=True, null=True)
    date_sent   = models.DateTimeField(verbose_name=_("Date"), auto_now_add=True)
    def __str__(self):
        return self.name
    class Meta:
        ordering = ('id',)
        verbose_name = 'Formulaire de contact'
        verbose_name_plural = 'Formulaire de contact'

class Quote(models.Model):
    name = models.TextField(verbose_name=_("la citation"))
    actif = models.BooleanField(default=True)
    autor = models.CharField(verbose_name=_("auteur"), max_length=100)
    function = models.CharField(verbose_name=_("Fonction"), max_length=100)
    image = models.ImageField(upload_to="images/")

    def __str__(self):
        return str(self.autor)

class Client(models.Model):
    name = models.CharField(max_length=50)
    logo = models.ImageField( upload_to="images/clients")

    def __str__(self):
        return self.name

class Article(models.Model):
    title         = models.CharField( max_length=150, verbose_name='Titre')
    slug          = models.SlugField()
    aperçu        = models.CharField( max_length=300, verbose_name='aperçu', blank=True, null=True)
    chapo         = models.CharField( max_length=300, verbose_name='chapô ',blank=True, null=True)
    quote         = models.CharField( max_length=300, verbose_name='phrase mise en avant ', blank=True, null=True)
    texte_haut    = tinymce_models.HTMLField(verbose_name='texte haut', blank=True, null=True)
    texte_bas     = tinymce_models.HTMLField(verbose_name='texte bas', blank=True, null=True)
    card_img     = models.ImageField(upload_to="images/")
    banner        = models.ImageField(upload_to="images/")
    publish       = models.BooleanField(default=True)
    actif         = models.BooleanField(default=True)
    created       = models.DateTimeField(verbose_name='Date de Création',  auto_now_add=True)
    updated       = models.DateTimeField(verbose_name='Date de dernière mise à jour',  auto_now=True)
    def __str__(self):
        return str(self.title)
    def get_absolute_url(self):
        return reverse("core:article_detail", kwargs={"slug": self.slug})

class Invoice(models.Model):
    client          = models.CharField(max_length=300,verbose_name='Client')
    client_rc       = models.CharField(max_length=300,verbose_name='RC Client')
    client_nif      = models.CharField(max_length=300,verbose_name='Nif Client')
    client_art      = models.CharField(max_length=300,verbose_name="Numéro d'article du client")
    client_adresse  = models.CharField(max_length=300,verbose_name='Adresse Client')
    client_phone    = models.CharField(max_length=300,verbose_name='Téléphone Client')
    client_email    = models.EmailField(max_length=300,verbose_name='Email Client')
    invoice_number  = models.IntegerField(verbose_name='Numéro de facture')
    invioce_date    = models.DateField(verbose_name=_("Date "), blank = True, null = True) 
    created       = models.DateTimeField(auto_now_add=True, verbose_name=_("Crée"))
    updated       = models.DateTimeField(auto_now=True, verbose_name=_("Modifié"))
    note          = models.TextField(blank=True, null=True, verbose_name=_("Note"))
    paid          = models.BooleanField(default=False, verbose_name=_("Payé"))
    discount      = models.DecimalField( max_digits=10, decimal_places=2, default=0, verbose_name="Réduction")

    def __str__(self):
        return f'facture N°:  {self.invoice_number} doit {self.client}'

    def save(self, *args, **kwargs):
        try:
            last_num = Invoice.objects.last().invoice_number
            self.invoice_number = last_num =+ 1
        except:
            self.invoice_number = 1
        super().save(*args, **kwargs) 
        return sum(item.get_cost() for item in self.items.all())


    def get_total_cost(self):
        items_cost = sum(item.get_cost() for item in self.items.all())
        total_cost = items_cost - self.discount
        # if total_cost < 0:
        #     total_cost = 0

        return total_cost




class InvoiceItem(models.Model):
    invoice    = models.ForeignKey(Invoice,related_name='items', verbose_name=(_("Facture")), on_delete=models.CASCADE)
    description = models.CharField(max_length=300,verbose_name='Description')
    price    = models.DecimalField( max_digits=10, decimal_places=2, verbose_name=_("Prix"))
    quantity = models.PositiveIntegerField(default=1, verbose_name=_("Quantité"))

    def __str__(self):
        return str(self.description)
    def get_cost(self):
        return self.price * self.quantity



class Offre(models.Model):
    title        = models.CharField(verbose_name=_('Offre'), max_length=100)
    description  = models.TextField( blank=True, null=True)
    service              = models.ForeignKey(Service, on_delete=models.CASCADE,blank=True, null=True)
    priority     = models.IntegerField(verbose_name=_('ordre / priorité'), blank=True, null=True)
    price_month         = models.DecimalField(max_digits=20, decimal_places=0, blank=True, null=True)
    price_year        = models.DecimalField(max_digits=20, decimal_places=0, blank=True, null=True)
    created      = models.DateTimeField(verbose_name='Date de Création',  auto_now_add=True)
    updated      = models.DateTimeField(verbose_name='Date de dernière mise à jour',  auto_now=True)

    def __str__(self):
        return self.title
    class Meta:
        ordering = ('id',)
        verbose_name = 'offre'
        verbose_name_plural = 'offres'   


class Fonctionalite(models.Model):
    title        = models.CharField( max_length=100)
    service      = models.ForeignKey(Service, on_delete=models.CASCADE,blank=True, null=True)
    description  = models.TextField( blank=True, null=True)
    priority  = models.IntegerField(verbose_name=_('ordre / priorité'), blank=True, null=True)
    created      = models.DateTimeField(verbose_name='Date de Création',  auto_now_add=True)
    updated      = models.DateTimeField(verbose_name='Date de dernière mise à jour',  auto_now=True)

    def __str__(self):
        return self.title
    class Meta:
        ordering = ('id',)
        verbose_name = 'fonctionalite'
        verbose_name_plural = 'fonctionalites' 

class Status(models.Model):
    offre                = models.ForeignKey(Offre, verbose_name=_("offre"), on_delete=models.CASCADE,blank=True, null=True)
    fonctionalite        = models.ForeignKey(Fonctionalite,related_name="status", verbose_name=_("fonctionalite"), on_delete=models.CASCADE,blank=True, null=True)
    included             = models.BooleanField(verbose_name="inclu dans l'offre", default=False)
    quantity             = models.CharField(verbose_name=_('quantité'), max_length=100,blank=True, null=True)
    created              = models.DateTimeField(verbose_name='Date de Création',  auto_now_add=True)

templates/blog.html
{% extends "base.html" %}
{% load static %}
{% block title %}
<title>OCTOPUS-CONSULTING | Blog</title>
{% endblock %}
{% block content %}

<body>
    <div class="main-page">
        <!-- Start Header -->
      
        <!-- Start Breadcrump Area  -->
        <div class="rn-page-title-area pt--120 pb--190 bg_image bg_image--1" data-black-overlay="5" style="background-image: url({% static 'images/bg-contact.png' %});">
        {% comment %} <div class="breadcrumb-area rn-bg-color ptb--120 bg_image bg_image--1" data-black-overlay="6" style="background-image:  url({% static 'images/bg-contact.png' %});"> {% endcomment %}
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="breadcrumb-inner pt--100 pt_sm--40 pt_md--50">
                            <h2 class="title">BLOG</h2>
                          
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Breadcrump Area  -->
        <main class="page-wrapper">
            <!-- Start blog Area  -->
            <div class="rn-blog-area rn-section-gap bg_color--1">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="section-title section-title--2 text-center">
                                <h2 class="title"> Nos articles</h2>
                                <p></p>
                            </div>
                        </div>
                    </div>
                    <div class="row mt--20">
                        {% for article in articles %}
                            <!-- Start Blog Area  -->
                            <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                                <div class="blog blog-style--1">
                                    <div class="thumbnail">
                                        <a href="{% url 'core:article_detail' article.slug %}"> 
                                            <img class="w-100" src="{{article.card_img.url}}" alt="Blog Images" />
                                        </a>
                                    </div>
                                    <div class="content">
                                        <p class="blogtype">{{article.title}}</p>
                                        <h4 class="title"><a "{% url 'core:article_detail' article.slug %}">{{article.aperçu}}..</a>
                                        </h4>
                                        <div class="blog-btn">
                                            <a class="rn-btn text-white" href="{% url 'core:article_detail' article.slug %}">Lire plus</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- End Blog Area  -->

                        {% endfor %}
                    </div>
                    {% comment %} <div class="row">
                        <div class="col-lg-12">
                            <div class="rn-pagination text-center mt--60 mt_sm--30">
                                <ul class="page-list">
                                    <li><a href="#">1</a></li>
                                    <li><a href="#">2</a></li>
                                    <li class="active"><a href="#">3</a></li>
                                    <li><a href="#">4</a></li>
                                    <li><a href="#"><i class="fas fa-angle-right"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div> {% endcomment %}
                </div>
            </div>
            <!-- Start blog Area  -->

      
        </main>
    
    </div>



</body>

</html>
{% endblock content %}

templates/blog_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
<title>OCTOPUS-CONSULTING | Blog</title>
{% endblock %}
{% block content %}
<body>
    <div class="main-page">
        <div class="rn-page-title-area pt--120 pb--190 bg_image bg_image--1" data-black-overlay="5" style="background-image: url({% static 'images/bg-contact.png' %});">
        {% comment %} <div class="rn-page-title-area pt--120 pb--190 bg_image bg_image--1" data-black-overlay="7" > {% endcomment %}
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                    <div class="breadcrumb-inner pt--100 pt_sm--40 pt_md--50">
                            <h2 class="title">BLOG</h2>
                          
                        </div>
                    
                    </div>
                </div>
            </div>
        </div>
        <!-- End Breadcrump Area  -->
        <!-- Start Page Wrapper  -->
        <main class="page-wrapper">

            <!-- Start Blog Details Area  -->
            <div class="rn-blog-details pt--110 pb--70 bg_color--1">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="inner-wrapper">
                                <div class="inner">
                                    <h2 >{{article.title}} </h2>
                                     <p >{{article.chapo}}</p>
                                    <div class="thumbnail">
                                        <img src="{{article.banner.url}}" alt="Blog Images">
                                    </div>
                                   {{article.texte_haut|safe}}
                                   
                                    <blockquote class="rn-blog-quote">&nbsp;  {{article.quote|safe}}  &nbsp;</blockquote>
                                      
                                      {{article.texte_bas|safe}}

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Blog Details Area  -->

            <!-- Start Comment Form  -->
          
            <!-- End Comment Form  -->

        </main>

    </div>



</body>

</html>
{% endblock content %}

templates/contact.html
{% extends "base.html" %}
{% load static %}
{% block title %}
<title>OCTOPUS-CONSULTING | Contact</title>
{% endblock %}
{% block content %}
        <!-- Start Breadcrump Area  -->
        <div class="rn-page-title-area pt--120 pb--190 bg_image bg_image--1" data-black-overlay="5" style="background-image: url({% static 'images/bg-contact.png' %});">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="breadcrumb-inner pt--100 pt_sm--40 pt_md--50">
                            <h2 class="title">CONTACTEZ-NOUS</h2>
                            <p style="color:#fff;">Nous vous recontacterons dans les 48H pour échanger sur votre projet</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Breadcrump Area  -->
        <!-- Start Page Wrapper  -->
        <main class="page-wrapper">
            <div class="rn-contact-address-area rn-section-gap bg_color--5">
                <div class="container">
                    <div class="row mt_dec--40">
                        <!-- Start Single Address  -->
                        <div class="col-lg-4 col-md-6 col-sm-6 col-12 mt--40">
                            <div class="rn-address">
                                <div class="icon">
                                    <i class="fas fa-phone"></i>
                                </div>
                                <div class="inner">
                                    <h4 class="title">Contactez nous par téléphone</h4>
                                    <p><a href="tel:{{business.phone}}">{{business.phone}}</a></p> <br>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6 col-sm-6 col-12 mt--40">
                            <div class="rn-address">
                                <div class="icon">
                                    <i class="fas fa-envelope"></i>
                                </div>
                                <div class="inner">
                                    <h4 class="title">Addresse Email </h4>
                                    <p><a href="mailto:{{business.email}}">{{business.email}}</a></p><br>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6 col-sm-6 col-12 mt--40">
                            <div class="rn-address">
                                <div class="icon">
                                    <i class="fas fa-map-marker-alt"></i>
                                </div>
                                <div class="inner">
                                    <h4 class="title">Localisation</h4>
                                    
                                    <p><a href="#section-map">{{business.adress}}</a></p><br>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="rn-contact-area rn-section-gap bg_color--1">
                <div class="contact-form--1">
                    <div class="container">
                        <div class="row row--35 align-items-start">
                            <div class="col-lg-6 order-2 order-lg-1">
                                <div class="section-title text-left mb--50 mb_sm--30 mb_md--30">
                                    <h2 class="title">Contactez nous.</h2>
                                    <p class="description">Nous vous recontacterons dans les 48H pour échanger sur votre projet. Entrer en contact avec nous par téléphone:
                                        <a href="tel:{{business.phone}}">{{business.phone}}</a> ou email:
                                        <a href="mailto:{{business.email}}"> {{business.email}}</a> </p>
                                </div>
                                <div class="form-wrapper">
                                    <div id="messageContact">
                                        {% if messages %}
                                            {% include 'snippets/message.html' %}
                                        {% endif %}
                                    </div>  
                                    <form  action="{% url 'core:contact' %}" method="post">
                                        {% csrf_token %}
                                        <input name="name"id="id_name"  type="text" placeholder="Votre nom*" required />
                                        <input name="email" id="id_email" type="email" placeholder="Votre e-mail *">
                                        <input name="phone" id="id_phone" type="phone" placeholder="Votre numéro de téléphone *">
                                        <input name="subject" id="id_subject" type="text" placeholder="Sujet">
                                        <textarea name="message" id="id_message" placeholder="Votre Message"></textarea>
                                        <button type="submit" class="rn-button-style--2 btn_solid">
                                            <span>Envoyer le message</span>
                                        </button>
                                    </form>
                                    {% comment %} <div class="form-output">
                                        <p class="form-messege-active form-messege"></p>
                                    </div> {% endcomment %}
                                </div>
                            </div>
                            <div class="col-lg-6 order-1 order-lg-2"> 
                                <div class="mb_md--40 mb_sm--40">
                                    <img src="{% static "images/contact.png" %}" alt="trydo"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="section-map" class="rn-brand-area brand-separation rn-section-gap">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3207.950605110489!2d2.8062816156271007!3d36.48290909319468!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x128f0dde61df1af3%3A0xb7fbfe86f236ee81!2sOctopus%20Consulting%20Digital%20Growth%20Agency!5e0!3m2!1sen!2sdz!4v1632671230887!5m2!1sen!2sdz"  style="border:0;width: 100%;height: 550px ;" allowfullscreen="true" loading="lazy"></iframe>
            </div>
        </main>
{% endblock content %}

templates/order_pdf.html
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <style>
            body {
                font-family:Helvetica, sans-serif;
                color:#222;
                line-height:1.5;
            }
            
            table {
                width:100%;
                border-spacing:0;
                border-collapse: collapse;
                margin:20px 0;
            }
            
            table th, table td {
                text-align:left;
                font-size:14px;
                padding:10px;
                margin:0;
            }
            
            tbody tr:nth-child(odd) {
                background:#efefef;
            }
            
            thead th, tbody tr.total {
                background: #15161D;
                color:#fff;
                font-weight:bold;
            }
            
            h1 {
                margin:0;
                color: #dfa667;
                text-transform: uppercase;
                  
            }
            
            
            .secondary {
                color:#bbb;
                margin-bottom:20px;
            }
            
            .num {
                text-align:right;
            }
            
            .paid, .pending {
                color:#184d47;
                border:4px solid #184d47;
                text-transform:uppercase;
                font-weight:bold;
                font-size:22px;
                padding:4px 12px 0px;
                float:right;
                transform: rotate(-15deg);
                margin-right:40px;
            }
            .pending {
                color:#c64756;
                border:4px solid #c64756;
            }
        </style>
    </head>
    <body>
        <h1>{{business}}</h1>
        <p>
            Commande Numéro° {{ invoice.id }} <br>
            <span class="secondary"> {{ invoice.created|date:"M d, Y" }} </span>
        </p>
        <h3>A l'ordre de </h3>
        <p>
            Monsieur/ Madame: {{ invoice.first_name }} {{ invoice.last_name }}<br>
            Email: {{ invoice.email }}<br>
            Adresse: {{ invoice.addresse }}<br>
            Wilaya: {{ invoice.wilaya.name }}<br>
            Commune: {{ invoice.commune.name }} <br>
            Livraison: {{invoice.delivery}} <br>
            {% if invoice.coupon %}
            Coupon: {{invoice.coupon.code}} <br>
            Réduction: {{invoice.discount_amount}} DA
            {% endif %}
        </p>
        <h3>Articles acheté :</h3>
        <table>
            <thead>
                <tr>
                    <th>Produit</th>
                    <th>Prix</th>
                    <th>Quantité</th>
                    <th>Total produit</th>
                </tr>
            </thead>
            <tbody>
                {% for item in invoice.items.all %}
                    <tr class="row{% cycle '1' '2' %}">
                        <td>{{ item.product.name }}</td>
                        <td class="num">{{ item.price }} DA</td>
                        <td class="num">{{ item.quantity }}</td>
                        <td class="num">{{ item.get_cost }} DA</td>
                    </tr>
                {% endfor %}
                <tr class="total">
                    {% if invoice.coupon %}
                    <td colspan="3">Total après réduction</td>
                    <td class="num">{{ invoice.get_total_cost}} DA</td>
                    {% else %}
                    <td colspan="3">Total</td>
                    <td class="num">{{ invoice.get_total_cost}} DA</td>
                    {% endif %}
                </tr>
            </tbody>
        </table>
        <span class="{% if invoice.paid %}paid{% else %}pending{% endif %}">
            {% if invoice.paid %}Payée{% else %}Non payée{% endif %}
        </span>
   </body>
   </html>

templates/services.html
{% extends "base.html" %}
{% load static %}
{% block title %}
<title>OCTOPUS-CONSULTING | Services</title>
{% endblock %}
{% block content %}
  
        <div class="rn-page-title-area pt--120 pb--190 bg_image bg_image--1" data-black-overlay="5" style="background-image: url({% static 'images/bg-contact.png' %});">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="breadcrumb-inner pt--100 pt_sm--40 pt_md--50">
                            <h2 class="title">NOS SERVICES</h2>
                            <!-- <ul class="page-list">
                                <li><a href="index.html">Home</a></li>
                                <li class="current-page">Service</li>
                            </ul> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Breadcrump Area  -->
        <main class="page-wrapper">
            <!-- Start Service Area  -->
            <div class="rn-service-area rn-section-gap bg_color--1">
                <div class="container">
                    <div class="row">
                        <!-- <div class="col-lg-12">
                            <div class="section-title text-center mb--30">
                                <h2>App Development</h2>
                                <p>There are many variations of passages of Lorem Ipsum available, <br> but the majority
                                    have suffered alteration.</p>
                            </div>
                        </div> -->
                    </div>
                    <div class="row">
                        {% for service in services %}
                            <!-- Start Single Service  -->
                            <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                                <div class="single-service service__style--4 large-size text-center">
                                    <a href="{{service.get_absolute_url}}">
                                        <div class="service">
                                            <div class="icon">
                                                <i class="{{service.icon}}"></i> 
                                            </div>
                                            <div class="content">
                                                <h3 class="title">{{service.name}}</h3>
                                                <p>{{service.title|truncatechars:70}}...</p>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </div>
                            <!-- End Single Service  -->
                        {% endfor %}


                    </div>
                </div>
            </div>
            <!-- Start Service Area  -->

        </main>
{% endblock content %}